### ISSUE TITLE
Missing flags import in handlers/shell.go

### ISSUE THREAD

**Issue by meling** [dgageot/demoit#16]
Tried demoit; it didn't compile out of the box, but it was easy to fix (see below). Also, for the install instructions, you don't need both `go build` and `go install`, only the install is necessary. Other than this great stuff...  Thanks.

```
diff --git a/handlers/shell.go b/handlers/shell.go
index 33ed52a..f5a7f79 100644
--- a/handlers/shell.go
+++ b/handlers/shell.go
@@ -25,6 +25,7 @@ import (
        "strings"

        "github.com/dgageot/demoit/files"
+       "github.com/dgageot/demoit/flags"
        "github.com/gorilla/mux"
        "github.com/pkg/errors"
 )
```

**Comment by qburst-samir** [comment]
@dgageot PR raised : https://github.com/dgageot/demoit/pull/17

**Comment by Deleplace** [comment]
Sorry about this! This should be fixed by now.
