### ISSUE TITLE
sh: -c: option requires an argument

### ISSUE THREAD

**Issue by petermbenjamin** [dgageot/demoit#2]
Thank you for this cool idea and project.
I decided to give it a try, but I seem to be hitting an error (see screenshot).

## Steps

1. `cd $HOME/go/src/github.com/dgageot/demoit`
1. `demoit sample` or `demoit -dev sample`
1. Visit http://localhost:9999 or http://127.0.0.1:9999

## Environment

- macOS 10.14.3
- chrome 71.0.3578.98
- safari 12.0.3
- go 1.11.4

## Screenshot

<img width="952" alt="screen shot 2019-01-29 at 9 40 42 am" src="https://user-images.githubusercontent.com/6811830/51928138-0c57bd80-23aa-11e9-81bd-591b917d2e93.png">

## Logs

```
$ !demoit
demoit -dev sample/
2019/01/29 09:49:14 Welcome to DemoIt. Please, open http://localhost:8888
2019/01/29 09:49:14 Permitting clients to write input to the PTY.
2019/01/29 09:49:14 HTTP server is listening at: http://:::9999/
[LiveReload] listening on :35729
2019/01/29 09:49:22 127.0.0.1:57360 200 GET /
2019/01/29 09:49:22 127.0.0.1:57360 200 GET /auth_token.js
2019/01/29 09:49:22 127.0.0.1:57362 200 GET /config.js
2019/01/29 09:49:22 127.0.0.1:57361 200 GET /css/index.css
2019/01/29 09:49:22 127.0.0.1:57364 200 GET /css/xterm_customize.css
2019/01/29 09:49:22 127.0.0.1:57363 200 GET /css/xterm.css
2019/01/29 09:49:22 127.0.0.1:57365 200 GET /js/gotty-bundle.js
2019/01/29 09:49:22 New client connected: 127.0.0.1:57366, connections: 1/0
2019/01/29 09:49:22 Connection closed by local command: 127.0.0.1:57366, connections: 0/0
```

**Comment by cdallagnola** [comment]
Hi, 

You have to open http://lcoahost:8888
You need to open it with Google chrome, doesn't work on Firefox.


Cédric

**Comment by petermbenjamin** [comment]
Doh!

You're right. Classic mistake of not reading instructions properly 🤦‍♂️ .

Just needed to hit port `:8888` not `:9999`.

Thank you !
