### ISSUE TITLE
Speaker notes

### ISSUE THREAD

**Issue by Deleplace** [dgageot/demoit#28]
Feature request: a separate browser window for Speaker notes.

Could be available on a separate port, or a separate handler.

The markup could use a custom element
```
<speaker-note>
This is what I will say, but it won't be displayed to the audience.
</speaker-note>
```

We would need to move forward the Speaker Notes view automatically when the steps move forward.

**Comment by Deleplace** [comment]
I ack that in the best presentations the Speaker looks at the audience, not at their notes. But not everyone has this skill, and the Speaker Notes can really help some speakers to deliver.

**Comment by Deleplace** [comment]
BroadcastChannel looks nice, for tabs sync.
https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel
https://caniuse.com/#feat=broadcastchannel

**Comment by Deleplace** [comment]
@dgageot I think I could design a "clean" implementation, orthogonal to all other features, thanks to BroadcastChannel.
Shall I?

**Comment by dgageot** [comment]
Go for it!

**Comment by Deleplace** [comment]
#55 was merged
