### ISSUE TITLE
Code preview misses last few lines

### ISSUE THREAD

**Issue by johanbrandhorst** [dgageot/demoit#32]
Hi, love this project, I'm evaluating it for future presentations. However, there seems to be a problem with the code preview pages in recent Firefox and Chromium versions:

Firefox 67.0b16:
![image](https://user-images.githubusercontent.com/6604151/57233310-4a522680-7016-11e9-9cc6-0f1cbfe2ce4a.png)

Chromium 74.0.3729.131 (Official Build) Arch Linux (64-bit):
![image](https://user-images.githubusercontent.com/6604151/57233374-6a81e580-7016-11e9-84c3-4d1d2e2ede13.png)

**Comment by dgageot** [comment]
This should be fixed by https://github.com/dgageot/demoit/commit/c179ac07cad5db6d052d95950ccac1135c57c0b1
