### ISSUE TITLE
Source file viewer ("source-code") is not scrollable horizontally

### ISSUE THREAD

**Issue by mehmandarov** [dgageot/demoit#46]
Text file viewer ("source-code") should offer horisontal scroll in case the lines in the file er too long. You can see the scrollbar at the bottom of the page, but can't scroll.

**Comment by dgageot** [comment]
Would you like to try and fix that?

**Comment by mehmandarov** [comment]
@dgageot: Please have a look. It is now in PR #53.

**Comment by mehmandarov** [comment]
Merged.
