### ISSUE TITLE
Terminal ("web-term") should be configurable via .bashrc

### ISSUE THREAD

**Issue by mehmandarov** [dgageot/demoit#47]
It would be great if one could specify .bashrc file (similar to .bash_history file we have now) that can be used to set up the terminal automatically at every view/load.

**Comment by dgageot** [comment]
That should really be easy to implement. Would you like to try? I can guide you

**Comment by mehmandarov** [comment]
Yes, I can have a look at this.

**Comment by mehmandarov** [comment]
@dgageot: Submitted. Please have a look. Feel free to improve the code if necessary. :-)

**Comment by mehmandarov** [comment]
Merged.
