### ISSUE TITLE
demoit crashs in the slide 7 of the sample

### ISSUE THREAD

**Issue by davidaparicio** [dgageot/demoit#68]
Hello David!

For information, when I run the sample, I got on http://localhost:8888/7

```
2022/11/04 17:16:15 unable to create a docker container for vscode: Error response from daemon: No such image: codercom/code-server:3.4.1
```

But, it's visible on the dockerhub..
https://hub.docker.com/layers/codercom/code-server/3.4.1/images/sha256-7595b2d20634b2546c94031adb554835d39e707f74cf6f4e783726be726dd8e3?context=explore

So, we need to perform a docker pull manually (to avoid the crash)

```
➜ docker pull codercom/code-server:3.4.1
3.4.1: Pulling from codercom/code-server
376057ac6fa1: Pull complete
e9328b5d4ce4: Pull complete
b235a90e52e2: Pull complete
050b6dc28509: Pull complete
e1d3f4aae495: Pull complete
13719612fc66: Pull complete
44f1c3cd316e: Pull complete
10e54f3cdd62: Pull complete
Digest: sha256:da8fe9ad6f6528b17e8d2fb927504e60d1e69527da165f69ffdf86f9d90b4c09
Status: Downloaded newer image for codercom/code-server:3.4.1
docker.io/codercom/code-server:3.4.1
```

Kind regards,
David

**Comment by dgageot** [comment]
Fixed with d8b2c171475209a1cc4b0d2b17b82fde22da83fb. Thanks for reporting!
